CREATE TABLE CLANE_ARTICLES(
  id IDENTITY NOT NULL PRIMARY KEY,
  title VARCHAR (100) NOT NULL,
  content VARCHAR (1000) NOT NULL
);

CREATE INDEX idx_article_id ON CLANE_ARTICLES(id);

CREATE TABLE CLANE_AUTHORS(
  id IDENTITY NOT NULL PRIMARY KEY,
  name VARCHAR (50) NOT NULL ,
  email VARCHAR (20) NOT NULL UNIQUE ,
  password VARCHAR (50) NOT NULL,
  bio VARCHAR (1000)
);

CREATE INDEX idx_author_id ON CLANE_AUTHORS(id);